/*


Given a long vector of strings, print the strings that contain the strings generated by numeric string str.

string searchIn [] = {
            "prateek", "sneha", "deepak", "arnav", "shikha", "palak",
            "utkarsh", "divyam", "vidhi", "sparsh", "akku"
    };

For example, if the input is 26 and the string is coding, then output should be coding since 26 can produce co which is contained in coding.
Input Format

A numeric string str
Constraints

len(str) < 10
No of strings in the vector < 10
Output Format

Each matched string from the given vector.
Sample Input

34

Sample Output

vidhi
divyam
sneha

Explanation

34 will result into combinations :

*dg         *eg         *fg
*dh            *eh         *fh
*di            *ei         *fi

Corresponding strings are output.

   1 vidhi contains dh
   2 divyam contains di
   3 sneha contains eh
*/

#include <iostream>
#include<string>
#include<bits/stdc++.h>
using namespace std;

char kp[][10] = {"", "", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz"};

string searchIn [] = {
            "prateek", "sneha", "deepak", "arnav", "shikha", "palak",
            "utkarsh", "divyam", "vidhi", "sparsh", "akku"
    };
 
 
void printKeypadString(char *in, char *out, int i, int j)
{
    if(in[i] == '\0')
    {
        out[j] = '\0';
       
       //converting char array to string
        int i;
        string s = "";
        for (i = 0; out[i] != '\0'; i++)
              s = s + out[i];
             
        //finding if the string is present as a substring
        for( i = 10; i >= 0; i--)
        {
            // *****************here I am getting no output why????????
              size_t found = searchIn[i].find(s);
               if (found != string::npos) {
                   cout << searchIn[i]<<endl;
               }
               
        }
        return;
    }
 
    int digit = in[i] - '0';
    // cout<<digit<<endl;
    for(int k = 0; kp[digit][k] != '\0'; k++){
      //   cout<<kp[digit][k]<<endl;
        out[j] = kp[digit][k];
        printKeypadString(in, out, i+1, j+1);
    }
    return;  
}
 
int main() {
    char a[10], b[10];
    cin>>a;
    printKeypadString(a, b, 0, 0);
    return 0;
}
